version: '3'
services: 
    nginx: 
        image: jiibon/nginx-php
        container_name: nginx
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./nginx:/etc/nginx/sites-enabled/
            - ./html:/usr/share/nginx/html/
            - ./logs:/var/logs/nginx/
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=db"
        #links:
        #    - db
        #depends_on:
        #    - db
    #db:
    #    image: 'mysql'
    #    container_name: mysql
    #    command: --default-authentication-plugin=mysql_native_password
    #    restart: always
    #    ports:
    #        - '3306:3306'
    #    volumes:
    #        - ./db:/var/lib/mysql
    #    environment:
    #        MYSQL_USER: root
    #        MYSQL_ROOT_PASSWORD: 123456
