version: '3'
services:
    nginx:
        image: jiibon/nginx-lemp
        container_name: nginx
        restart: always
        links:
            - phpfpm
        volumes:
            - ./nginx:/etc/nginx/sites-enabled
            - ./html:/usr/share/nginx/html
            - ./logs:/var/logs/nginx
    phpfpm:
        image: php:7.2.10-fpm-alpine
        container_name: php-fpm
        restart: always
        volumes:
            - ./html:/usr/share/nginx/html
